version: '3.9'

services:
    gateway:
        image: nginx:1.18
        ports:
        -   "7000:7000"
        -   "7001:7001"
        volumes:
            - ./gateway/docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            -   frontend
            -   api
    frontend:
        image: nginx:1.18
        volumes:
            - ./frontend/docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./frontend:/www
        working_dir: /www
    api:
        image: nginx:1.18
        volumes:
            - ./api/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./api:/www
        working_dir: /www
        links:
            - api-fpm
    api-fpm:
        build: ./api/docker/fpm
        ports:
            - "7002:9000"
        volumes:
            - ./api:/www
        working_dir: /www
        environment:
            PHP_IDE_CONFIG: serverName=api
        links:
            - api-mysql
    api-cli:
        build: ./api/docker/cli
        volumes:
            - ./api:/www
        working_dir: /www
    api-mysql:
        image: mariadb:10.5
        ports:
            - "7003:3306"
        volumes:
            - .:/www
        working_dir: /www
        environment:
            MYSQL_DATABASE: api-mysql
            MYSQL_ROOT_PASSWORD: qwerty
            MYSQL_USER: root
