version: '3.9'

services:
    api-web:
        image: nginx:1.18
        ports:
            - "7000:80"
        volumes:
            - ./api/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/www
        working_dir: /www/api
        links:
            - api-fpm
    api-fpm:
        build: ./api/docker/fpm
        ports:
            - "7001:9000"
        volumes:
            - .:/www
        working_dir: /www/api
        links:
            - api-mysql
    api-mysql:
        image: mariadb:10.5
        ports:
            - "7002:3306"
        volumes:
            - .:/www
        working_dir: /www/api
        environment:
            MYSQL_DATABASE: api-mysql
            MYSQL_ROOT_PASSWORD: qwerty
            MYSQL_USER: root
